# Generated by Django 3.0.6 on 2020-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=1)),
                ('yearofbirth', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videosread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('videoid', models.IntegerField()),
            ],
            options={
                'db_table': 'videosread',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tags', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('lang', models.CharField(blank=True, max_length=2, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('nbpeakers', models.IntegerField(blank=True, null=True)),
                ('kindspeakers', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=35, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'videos',
                'managed': True,
            },
        ),
    ]
