# Generated by Django 3.0.6 on 2020-05-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200507_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoread',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='videoread',
            old_name='videoid',
            new_name='video',
        ),
    ]
